Simple zce instructions
openhwgroup/cv32e41p pull request #18
Opened 2022-02-08 11:13 UTC by abukharmeh

Adds the simple subset of ZCE instructions

2022-02-09 18:03 UTC, davideschiavone requested changes
I suggest to check trilling white spaces and indentation - sublime and/or verible should help :)
This causes also more readable code on Github

2022-02-10 18:16 UTC, abukharmeh commented
Thanks @davideschiavone, will do that and let you know.

2022-02-17 12:09 UTC, davideschiavone commented
I think you should rebase to solve those conflicts

2022-02-17 13:07 UTC, abukharmeh commented on rtl/cv32e41p_merged_decoder.sv
> +                        end
I am not sure this is the best approach, perhaps I should have completely disabled the vector operations of the ALU, and just introduced sext and zext as two independent operations. I remember trying to look at that, but then thought of #13. Perhaps, I should look into this depending on how it synthesis when I remap the instructions to 0.7

2022-03-01 16:23 UTC, abukharmeh commented
@davideschiavone  ping, any suggestions or comments ?

2022-03-02 14:03 UTC, merged

2022-03-02 14:03 UTC, davideschiavone commented
LGTM